# Generated by Django 4.2.2 on 2023-06-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portafolio',
        ),
    ]
